# jenkins.yml
version: "3.5"

services:
    jenkins:
        image: jenkins/jenkins:lts
        volumes:
            - jenkins_home:/var/jenkins_home
        networks:
            - jenkins
        ports:
            -   '8080:8080'
            
    jenkins-agent:
        build:
            context: .
            dockerfile: docker/jenkins/Dockerfile
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /tmp/jenkins:/tmp/jenkins
        ports:
            -   '8080:8080'
        secrets:
            - jenkins-password
        networks:
            - jenkins

secrets:
    jenkins-password:
        external: true

volumes:
    jenkins_home:

networks:
    jenkins:
