# docker-compose.ci.yml

version: '3.5'
services:

    jenkins:
        container_name: jenkins
        image: localhost:5000/jenkins
        build:
            context: ./docker/master
        ports:
            - '8080:8080'
            - '50000:50000'
        environment:
            - JENKINS_HOME=${JENKINS_HOME}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - JENKINS_URL=${JENKINS_URL}
            - JENKINS_USER=${JENKINS_USER}
            - JENKINS_PASS=${JENKINS_PASS}
            - GITHUB_USER=${GITHUB_USER}
            - GITHUB_PASS=${GITHUB_PASS}
            - GIT_API_TOKEN=${GIT_API_TOKEN}
        volumes:
            - jenkins-master:/var/jenkins_home
            - ./config:/usr/share/jenkins/ref/init.groovy.d/

    jenkins-slave:
        container_name: jenkins-slave
        image: localhost:5000/jenkins-slave
        build:
            context: ./docker/slave
        environment:
            - JENKINS_URL="${JENKINS_URL}"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
            - ./scripts:/var/lib/jenkins/scripts
        depends_on:
            - jenkins
        restart: always

volumes:
    jenkins-master:
    # jenkins-worker:
