# docker-compose.ci.yml

version: '3.1'
services:
    jenkins:
        container_name: jenkins
        image: localhost:5000/jenkins
        build:
            context: ./docker/master
        ports:
            - '8080:8080'
            - '50000:50000'
    jenkins-slave:
        container_name: jenkins-slave
        image: localhost:5000/jenkins-slave
        build:
            context: ./docker/slave
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
            - /home/jenkins:/home/jenkins # Avoid mysql volume mount issue
        depends_on:
            - jenkins
        restart: always

# 1dfcb5730b5bd8de6fdff14dd1d7592e3d9fe21e